### ISSUE TITLE
[마진 이슈] 슬라이드 5번정도에서 아래와 같은 레이아웃 이슈가 발생하였습니다.

### ISSUE THREAD

**Issue by rxYoungho** [suyeon1109/korea-startup-landingpage#2]
안녕하세요, 교육목적으로 활용하려고 하다보니 아래 이슈가 발생하였습니다.

OS: MacOS

Browser: Chrome 109.11

이슈: 슬라이드 5번의 칸 벌어짐 현상

사진: 
![image](https://user-images.githubusercontent.com/44015667/200304726-c7580c0f-3431-4cfd-bd4f-3fee0e7a2184.png)

**Comment by suyeon1109** [comment]
감사합니다 수정 완료되었습니다.
